// import { Inter } from 'next/font/google'
import React from 'react'
import './globals.css'
import ReduxStoreProvider from '../redux/provider'
import Sidebar from "../components/misc/Sidebar/Sidebar"
import MobBotNav from '../components/misc/mobailBottomNav/MobaiBottomNav'
import Header from '../components/misc/header/Header'
import { useRouter } from 'next/navigation'



import { sessionStatus} from "./(auth)/login/_components/LoginForm";


// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'EUT',
  description: 'Generated by create next app',
}
// const token = localStorage.getItem("tokenSession");
export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body>
        <ReduxStoreProvider >
          
        { <Header />}
        <div className='flex '>
       
            { <Sidebar /> }
            <div className=' h-[100vh] lg:pt-[10vh] md:pt-[10vh] sm:pt-[10vh] pt-[7vh] w-full bg-[#E1EFF2] overflow-x-hidden '>
              <div className=' bg-white  w-full overflow-y-auto  max-h-full lg:rounded-tl-xl md:rounded-tl-xl sm:rounded-tl-xl rounded-tl-none'>
                {children}
              </div>
            </div>
          </div>
          <MobBotNav />
        </ReduxStoreProvider >
      </body>
    </html>
  )
}
